import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ScrollText, CheckCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';

const TERMS_VERSION = 'v1.0';
const TERMS_KEY = `accubooks_terms_accepted_${TERMS_VERSION}`;

export function hasAcceptedTerms() {
  return localStorage.getItem(TERMS_KEY) === 'true';
}

export function acceptTerms() {
  localStorage.setItem(TERMS_KEY, 'true');
}

export default function TermsOfUse({ onAccept, showAcceptButton = false }) {
  const navigate = useNavigate();
  const [accepted, setAccepted] = useState(false);

  const handleAccept = () => {
    acceptTerms();
    if (onAccept) onAccept();
    else navigate('/');
  };

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <div className="max-w-3xl mx-auto w-full px-4 py-10 flex-1">
        <div className="flex items-center gap-3 mb-8">
          <div className="w-10 h-10 rounded-lg bg-primary flex items-center justify-center">
            <ScrollText className="w-5 h-5 text-primary-foreground" />
          </div>
          <div>
            <h1 className="text-2xl font-heading font-bold">AccuBooks — Terms of Use</h1>
            <p className="text-sm text-muted-foreground">Effective date: July 2026 · Version {TERMS_VERSION}</p>
          </div>
        </div>

        <div className="prose prose-sm max-w-none space-y-6 text-foreground">

          <section>
            <h2 className="text-base font-semibold mb-2">1. Acceptance of Terms</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              By accessing or using AccuBooks ("the Application"), you agree to be bound by these Terms of Use. If you do not agree to these terms, you may not use the Application. These terms apply to all users, including administrators and standard users.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-2">2. Description of Service</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              AccuBooks is a business management application that enables users to manage customers, products, quotes, sales orders, invoices, and credit notes. The Application is provided as a software tool to assist with business operations and does not constitute professional accounting, legal, or financial advice.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-2">3. User Responsibilities</h2>
            <ul className="text-sm text-muted-foreground leading-relaxed list-disc pl-5 space-y-1">
              <li>You are responsible for maintaining the confidentiality of your login credentials.</li>
              <li>You must ensure that all data entered into the Application is accurate and lawful.</li>
              <li>You may not use the Application for any unlawful purpose or in violation of any applicable laws.</li>
              <li>You are responsible for compliance with all applicable tax, VAT, and financial regulations in your jurisdiction.</li>
              <li>You must not attempt to gain unauthorised access to any part of the Application or its underlying systems.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-2">4. Data and Privacy</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Your data (including customer records, financial documents, and company settings) is stored securely. You retain ownership of all data you enter into the Application. We do not sell or share your data with third parties except as required to operate the service (e.g., email delivery). You are responsible for ensuring your use of customer data complies with the Protection of Personal Information Act (POPIA) and any other applicable data protection legislation.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-2">5. Financial Documents Disclaimer</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Documents generated by the Application (quotes, invoices, credit notes, etc.) are based solely on the information you provide. AccuBooks does not verify the accuracy of figures, VAT calculations, or compliance with SARS requirements. You remain solely responsible for the correctness and legality of all documents issued to your customers. We recommend that all financial documents be reviewed by a qualified accountant.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-2">6. Intellectual Property</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              The Application, including its design, code, and features, is the intellectual property of the Application owner. You are granted a limited, non-exclusive, non-transferable licence to use the Application for its intended business purposes only.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-2">7. Limitation of Liability</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              To the maximum extent permitted by law, AccuBooks and its developers shall not be liable for any direct, indirect, incidental, or consequential damages arising from your use of the Application, including but not limited to loss of data, financial loss, or errors in generated documents. The Application is provided "as is" without warranty of any kind.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-2">8. Changes to Terms</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              These terms may be updated from time to time. Continued use of the Application after changes are published constitutes acceptance of the revised terms. Users will be notified of material changes upon next login.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-2">9. Governing Law</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              These Terms of Use are governed by the laws of the Republic of South Africa. Any disputes shall be subject to the exclusive jurisdiction of the South African courts.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-2">10. Contact</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              If you have any questions about these Terms of Use, please contact the system administrator of your AccuBooks instance.
            </p>
          </section>
        </div>

        {showAcceptButton && (
          <div className="mt-10 border-t border-border pt-6">
            <label className="flex items-start gap-3 cursor-pointer mb-5">
              <input
                type="checkbox"
                className="mt-0.5 w-4 h-4 accent-primary"
                checked={accepted}
                onChange={(e) => setAccepted(e.target.checked)}
              />
              <span className="text-sm text-muted-foreground">
                I have read and agree to the AccuBooks Terms of Use.
              </span>
            </label>
            <Button onClick={handleAccept} disabled={!accepted} className="gap-2">
              <CheckCircle className="w-4 h-4" />
              Accept & Continue
            </Button>
          </div>
        )}

        {!showAcceptButton && (
          <div className="mt-8 border-t border-border pt-6">
            <Button variant="outline" onClick={() => navigate(-1)}>← Back</Button>
          </div>
        )}
      </div>
    </div>
  );
}